name: Maluta's Blog
description: Notes on things
url: http://maluta.github.io
markdown: rdiscount
pygments: true
permalink: /blog/:title
auto: true
analytics:
  provider: google
  google:
     tracking_id: 'UA-46174575-1'
rdiscount:
  extensions: [smart]
