markdown: rdiscount
pygments: true
permalink: /blog/:title
auto: true
comments:
  provider: disqus
  disqus:
     short_name: maluta
analytics:
  provider: google
  google:
     tracking_id: 'UA-46174575-1'
rdiscount:
  extensions: [smart]
