--- 
title: "Notas diárias"
author: "Tiago Maluta"
#date: "`r Sys.Date()`"
date: "Julho 2019"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: ""
---

# xxxxx 

Ainda lembro quando existia um controle muito maior da plataforma e do conteúdo. 

Tudo é proporcionalmente mais difícil. Qualquer um que tivesse curiosidade técnica podia rapidamente criar um espaço "só seu" para publicar o que quisesse. Recordo de bater cabeça, por volta do ano de 2002, com páginas usando HTML escritas dentro do bloco de notas, depois conhecendo o [FrontPage](https://pt.wikipedia.org/wiki/Microsoft_FrontPage) e outras coisas que nunca me aprofundei pois eram pesadas demais para meu computador a época mas que lembro que eram A ferramenta, como o [DreamWeaver](https://en.wikipedia.org/wiki/Adobe_Dreamweaver#Version_history) (pré-Adobe) até, dando um salto no tempo, já na faculdade me animar com o [Wordpress](https://wordpress.com/) e durante o mesmo período a felicidade em conhecer a filosofia do [Jekyll](https://jekyllrb.com/)

No paralelo a conveniência permitiu que muito mais gente tivesse espaço para conteúdo. Os números das redes sociais, Facebook _et all_, não mentem. Sem entrar no mérito do preço que todos nós pagamos ao virarmos insumos na máquina de propaganda digital. A utopia é que lá posso me expressar para meus amigos. 




